perf(utils): extract lodash.merge
AttoJS/vue-request pull request #45
Opened 2021-05-21 07:29 UTC by Duncan-zjp

perf(utils): extract lodash.merge

2021-05-21 07:50 UTC, John60676 commented on .gitignore
> -coverage
这个配置不要改

2021-05-21 07:51 UTC, John60676 requested changes

2021-05-21 07:51 UTC, John60676 commented on src/core/utils/lodash/merge.ts
> +const mergeObj = (oriObj: object, target: object) => {
类型不要用 `object` 换成 `Record<string, any>`

2021-05-21 07:55 UTC, John60676 requested changes

2021-05-21 07:55 UTC, John60676 commented on src/core/utils/index.ts
> +export const isPlainArray = (val: unknown): val is Record<string, any> =>
`Array.isArray`

2021-05-21 08:56 UTC, benny-eu requested changes

2021-05-21 08:56 UTC, benny-eu commented on src/core/utils/lodash/merge.ts
> +  for (let i = 0; i < other.length; i++) {
for...of

2021-05-22 06:02 UTC, John60676 approved these changes

2021-05-22 06:03 UTC, merged